// src/modules/auth/components/login-form.tsx
'use client'

import { Input } from '@/components/ui/input'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage
} from '@/components/ui/form'

import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { LoginSchema, loginSchema, signInUser } from '..'
import toast from 'react-hot-toast'
import { Button } from '@/components/ui/button'
import { useRouter } from 'next/navigation'
import { useState } from 'react'

export default function LoginForm() {
  const [isLoginLoading, setIsLoginLoading] = useState<boolean>(false)
  const router = useRouter()
  const form = useForm({
    resolver: zodResolver(loginSchema),
    defaultValues: {
      email: '',
      password: ''
    }
  })

  const onSubmit = async (inputData: LoginSchema) => {
    const { email, password } = inputData

    try {
      setIsLoginLoading(true)
      await signInUser({ email, password })
    } catch (_) {
      toast.error('Unknown error occured')
    } finally {
      setIsLoginLoading(false)
    }
  }

  return (
    <div className="bg-card w-md rounded-lg p-6 shadow-md">
      <h2 className="text-primary mb-6 text-center text-2xl font-bold">
        Login
      </h2>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Email</FormLabel>
                <FormControl>
                  <Input
                    type="email"
                    placeholder="juantamad@gmail.com.ph"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Password</FormLabel>
                <FormControl>
                  <Input
                    type="password"
                    placeholder="Enter your password"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <div className="flex flex-col gap-2">
            <Button disabled={isLoginLoading} type="submit" className="w-full">
              {isLoginLoading ? 'Submitting...' : 'Login'}
            </Button>
            <Button
              disabled={isLoginLoading}
              onClick={() => router.push('/register')}
              variant="link"
              className="w-full"
              type="button"
            >
              Don&apos;t have account? Register here.
            </Button>
          </div>
        </form>
      </Form>
    </div>
  )
}

// frontend/src/modules/auth/login/login-form.svelte
<script lang="ts">
	import * as Form from '$lib/components/ui/form';
	import { Input } from '$lib/components/ui/input';
	import { defaults, superForm } from 'sveltekit-superforms';
	import { zod } from 'sveltekit-superforms/adapters';
	import { loginSchema } from '../';
	import { Button } from '$lib/components/ui/button';
	import { goto } from '$app/navigation';

	const form = superForm(defaults(zod(loginSchema)), {
		SPA: true,
		validators: zod(loginSchema)
	});

	const { form: formData, enhance } = form;
</script>

<form class="w-full max-w-md rounded-lg border p-3" method="POST" use:enhance>
	<div class="mb-5 text-center">
		<h1 class="text-3xl font-bold">Login</h1>
		<p>Login now to start managing your gym business</p>
	</div>
	<div>
		<Form.Field {form} name="email">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Email</Form.Label>
					<Input type="email" {...props} bind:value={$formData.email} />
				{/snippet}
			</Form.Control>
			<Form.FieldErrors />
		</Form.Field>
		<Form.Field {form} name="password">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Password</Form.Label>
					<Input type="password" {...props} bind:value={$formData.password} />
				{/snippet}
			</Form.Control>
			<Form.FieldErrors />
		</Form.Field>
	</div>
	<div class="mt-10">
		<Form.Button type="submit" class="w-full">Login</Form.Button>
		<Button variant="link" onclick={() => goto('/register')} type="button" class="mt-3 w-full"
			>Don&apos;t have account yet?</Button
		>
	</div>
</form>
